---
- name: Generate VLAN
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Delete VLAN
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:

        - name: Delete VLAN with name or TAG
          exos_config:
            lines: 
              - >-
                {% if lookup('vars', 'VLAN_NAME_' + item, default='') != '' %}
                delete vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} 
                {% elif lookup('vars', 'TAG_ID_' + item, default='') != '' %}
                {% endif %}
          loop: "{{ vlan_items }}"
