---
- name: Generate VLAN
  hosts: sw
  connection: network_cli
  gather_facts: false

  collections:
    - community.network

  tasks:
    - name: Delete VLAN
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:
        - name: Delete VLAN with name or TAG
          community.network.exos_config:
            lines: 
              - "delete vlan {{ lookup('vars', 'VLAN_NAME_' + item) }}"
          loop: "{{ vlan_items }}"
          ignore_errors: True