---
- name: Generate
  hosts: sw
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network

  tasks:
    - name: SET EAPS
      vars:
        vlan_items: "{{ range(1, num_eaps_vlan + 1) | map('string') | list }}"
      block:
        - name: Eaps Create and Mode Assign
          debug:
            msg: 
              - "configure eaps {{ lookup('vars', 'EAPS_Name_' + item) }} add {{ lookup('vars', 'EAPS_Type_' + item) }} vlan {{ lookup('vars', 'EAPS_VLAN_Name_' + item) }}"
          loop: "{{ vlan_items }}"
          ignore_errors: True
