---
- name: Create and rename a file in /tmp directory
  hosts: localhost  # Assuming you're running this playbook on the local machine
  gather_facts: no
  become: false

  tasks:
    - name: Create a file new2_file.txt
      file:
        path: /tmp/new2_file.txt
        state: touch

    - name: Rename new2_file.txt to kotha_file.txt
      command: mv /tmp/new2_file.txt /tmp/kotha_file.txt
      args:
        creates: /tmp/kotha_file.txt
      changed_when: false
      when: not ansible_check_mode
