---
- name: Create, rename, and push a file to GitHub repo
  hosts: localhost  # Assuming you're running this playbook on the local machine
  gather_facts: no
  become: false

  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Create a file new3_file.txt
          file:
            path: /tmp/new3_file.txt
            state: touch
          when: not ansible_check_mode

        - name: Rename new3_file.txt to kotha_file2.txt
          command: mv /tmp/new3_file.txt /tmp/kotha_file2.txt
          args:
            creates: /tmp/kotha_file2.txt
          changed_when: false
          when: not ansible_check_mode

        - name: Add exception for /tmp directory in Git
          command: git config --global --add safe.directory /tmp
          when: not ansible_check_mode

        - name: push to git
          shell: "{{ item }}"
          args: 
            chdir: /tmp
          loop: 
            - git config --global user.name "shezanhossain"
            - git config --global user.email shezan_hossain.mahmud@smail.th-koeln.de
            - git init
            - git remote add origin https://shezanhossain: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@github.com/shezanhossain/awx_try2.git
            - git add *
            - git commit -m "try2"
            - git push origin master