---
- name: Gather Fact
  hosts: sw
  gather_facts: no

  tasks: 
    - name: Gather the config facts
      community.network.exos_facts:
        gather_subset: all
      register: all_subset   

    - name: Print Subset All
      debug:
        var: all_subset