---
- name: Display localhost information
  hosts: all
  gather_facts: false
  tasks:
    - name: Display localhost details
      debug:
        msg: "This is {{ ansible_hostname }} with IP address {{ ansible_default_ipv4.address }}"
      delegate_to: localhost