---
- name: Display localhost information
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Display localhost details
      debug:
        msg: "This is {{ ansible_hostname }} with IP address {{ ansible_default_ipv4.address }}"
