---
- name: Show config
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Show config
    community.network.exos_command:
      commands: show config vlan
    register: config

  - name: Save Output to ~/network-prog/backups/
    copy: 
      content: "{{config.stdout[0]}}"
      dest: "~/var/lib/awx{{inventory_hostname}}"
