---
- name: Show config
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Show config
    community.network.exos_command:
      commands: show config vlan
    register: config_result

  - name: Display Config to sort
    debug:
      msg: |
        {{ inventory_hostname }} @@@ {{ config_result.stdout[0] }} @@@