---
- name: Show config
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Show config
    community.network.exos_command:
      commands: show config
    register: config

  - name: Save Output
    debug:
      var: config.stdout