---
- name: Show config
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Get switch configuration
      exos_command:
        commands: show config vlan
      register: config_output

    - set_fact:
        switch_outputs: "{{ switch_outputs | default({}) | combine({ inventory_hostname: config_output.stdout }) }}"

    - debug:
        var: switch_outputs
