---
- name: Generate
  hosts: all
  ansible_network_os: exos
  connection: network_cli
  gather_facts: false

  tasks: 
    - name: Create VLAN name 
      community.network.exos_config:
        lines: 
          - "create vlan IT"