---
- name: Test SSH connection to Extreme Switch
  hosts: sw
  gather_facts: no


  tasks:
  - name: run show version on remote devices
    exos_command:
      commands: show version
    register: version

  - name: Show registered variable output
    debug:
      var: version.stdout