---
- name: version check
  hosts: sw
  connection: network_cli
  gather_facts: false

  tasks:
  - name: run show version on remote devices
    exos_command:
      commands: show version | grep SysName
    register: version

  - name: Show registered variable output
    debug:
      var: version.stdout