---
- name: Test SSH connection to Extreme Switch
  hosts: sw
  gather_facts: no

  tasks: 
    - name: Test for user1
      local_action: 
        module: shell
        args: ssh shezan@{{ ansible_host }} "show switch | grep SysName"
      register: user1_enabled
      become: no

    - name: Show registered variable output
      debug:
        var: user1_enabled.stdout