---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  vars:
    vlan_names: {}  # Initialize an empty dictionary to store VLAN names

  tasks:
    - name: Set VLANs
      exos_config:
        lines:
          - "create vlan {{ item.key }} tag={{ item.value }}"
      loop: "{{ vlan_names | dict2items }}"



