---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set External VLANs
      set_fact:
        vlans: "{{ external_vlans }}"

  tasks:
    - name: Set VLANs
      exos_config:
        lines:
          - "create vlan {{ external_vlans }}"
      
