---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set VLANs
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      #vars: {{ "VLAN_NAME_"+ item }}
      block:

        - name: Create VLAN
          debug:
            msg: "create vlan VLAN_NAME_{{ item }}"
          loop: "{{ vlan_items }}"
          when: lookup('vars', 'PORT_NUM_' + item, default='') != ''

        - name: Add Ports to VLAN
          debug:
            msg: "configure vlan VLAN_NAME_{{ item }} add ports {{ lookup('vars', 'PORT_NUM_' + item) }}"
          loop: "{{ vlan_items }}"
          when: lookup('vars', 'PORT_NUM_' + item, default='') != ''
