---
- name: Get Ansible Version
  hosts: sw1
  become: yes

  tasks:
    - name: Check Ansible Version
      command: ansible --version
      register: ansible_version_output

    - name: Display Ansible Version
      debug:
        var: ansible_version_output.stdout_lines
