---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  vars:
    a: { num }
    vlan_ids: {}

  tasks:
    - name: Generate VLAN IDs
      set_fact:
        vlan_ids["ID_" + item] : "{{ item }}"
      loop: "{{ range(1, a+1) | map('string') | list }}"

    - name: Set VLANs
      exos_config:
        lines:
          - "create vlan {{ item }}"
      loop: "{{ vlan_ids.keys() | list }}"


