---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set VLANs
      loop: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      #vars: {{ "VLAN_NAME_"+ item }}
      vars:
        vlan_name: "{{ lookup('vars', 'VLAN_NAME_' + item) }}"
        port_num: "{{ lookup('vars', 'PORT_NUM_' + item) }}"
      when: port_num is defined and port_num != ""

      block:
        - name: Debug create vlan
          debug:
            msg: 
              - "create vlan {{ vlan_name }}"
        - name: Debug add ports
          debug:
            msg: 
              - "configure vlan {{ vlan_name }} add ports {{ port_num }}"
