---
- name: Generate VLAN
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set External VLANs
      set_fact:
        vlans: "{{ external_vlans }}"

  tasks:
    - name: Set VLANs
      exos_config:
        lines:
          - "create vlan {{ item.vlan_name }}"
        loop: "{{ vlans }}"
