---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set VLANs
      loop: "{{ range(1, num_vlans + 1) | list }}"
      exos_config:
        lines:
          - "create vlan ID_{{ item }} name {{ lookup('env', 'VLAN_NAME_' + item) }}"




