---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  vars:
    vlan_num: 2

  tasks:
    - name: Set VLANs
      exos_config:
        lines:
          - "create vlan {{ 'ID_' + item }}"
      loop: "{{ range(1, vlan_num+1) | map('string') | list }}"

