---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false
  
  tasks:
    - name: SET VLAN
      vars:
        vlan_items: "{{ range(1, num_vlans + 1) | map('string') | list }}"
      block:

        - name: Create VLAN name and TAG
          exos_config:
            lines: 
              - "create vlan {{ lookup('vars', 'VLAN_NAME_' + item) }}"
              - >-
                {% if lookup('vars', 'TAG_ID_' + item, default='') != '' %}
                configure vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} tag {{ lookup('vars', 'TAG_ID_' + item) }}
                {% endif %}
          loop: "{{ vlan_items }}"

          register: vlan_result

        - name: Add Ports to VLAN with or without TAG
          exos_config:
            lines: 
              - >-
                {% if lookup('vars', 'TAGGED_' + item, default='').lower() == 'y' %}
                configure vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} add ports {{ lookup('vars', 'PORT_NUM_' + item) }} tagged
                {% else %}
                configure vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} add ports {{ lookup('vars', 'PORT_NUM_' + item) }} untagged
                {% endif %}
          loop: "{{ vlan_items }}"
          when: lookup('vars', 'PORT_NUM_' + item, default='') != ''

          register: ports_result

        - name: Allocate VLAN IP 
          # vlan ip must be set in the quatation (""), like a string
          exos_config: 
            lines: 
              - >-
                {% if lookup('vars', 'IP_' + item, default='') != '' and lookup('vars', 'SUBNET_' + item, default='') %}
                configure vlan {{ lookup('vars', 'VLAN_NAME_' + item) }} ipaddress {{ lookup('vars', 'IP_' + item) }} {{ lookup('vars', 'SUBNET_' + item) }}
                {% endif %}
          loop: "{{ vlan_items }}"
          when: lookup('vars', 'IP_' + item, default='') != '' and lookup('vars', 'SUBNET_' + item, default='') != ''

          register: ip_result

        - name: Save VLAN Output
          always:
            - name: Store VLAN Output
              copy:
                content: "{{ vlan_result.stdout_lines | join('\n') }}"
                dest: "{{ playbook_dir }}/output_vlan.txt"
              when: vlan_result is defined

        - name: Save Ports Output
          always:
            - name: Store Ports Output
              copy:
                content: "{{ ports_result.stdout_lines | join('\n') }}"
                dest: "{{ playbook_dir }}/output_ports.txt"
              when: ports_result is defined

        - name: Save IP Output
          always:
            - name: Store IP Output
              copy:
                content: "{{ ip_result.stdout_lines | join('\n') }}"
                dest: "{{ playbook_dir }}/output_ip.txt"
              when: ip_result is defined
