---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false
  
  tasks:
    - name: Set VLANs
      loop: "{{ (range(1, num_vlans + 1) | map('string')) | list }}"
        vars: {{ "VLAN_NAME_"+ item }}
        debug:
          msg:
            - "create vlan {{ "VLAN_NAME_"+ item  }}"







