---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false
  
  tasks:
    - name: Set VLANs
      loop: "{{ (range(1, num_vlans + 1) | map('string')) | list }}"
      debug:
        msg: 
         - create vlan {{ lookup("vars", "VLAN_NAME_"+ item) }}
         - "{{ 'configure vlan ' + lookup('vars', 'VLAN_NAME_' + item | string) + ' add ports ' + lookup('vars', 'PORT_NUM_' + item | string) if lookup('vars', 'PORT_NUM_' + item | string) is defined and lookup('vars', 'PORT_NUM_' + item | string) != None else '' }}"
