---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false
  
  tasks:
    - name: Set VLANs
      loop: "{{ (range(1, num_vlans + 1) | map('string')) | list }}"
      set_fact:
        vlan_msg: "create vlan {{ lookup('vars', 'VLAN_NAME_'+ item) }}"
      register: vlan_output

    - name: Save Output to File
      copy:
        content: "{{ vlan_output.results | map(attribute='ansible_facts.vlan_msg') | join('\n') }}"
        dest: "{{ ansible_playbook_dir }}/output.txt"
