---
- name: Generate VLAN
  hosts: sw1
  connection: network_cli
  gather_facts: false

  vars:
    vlans:
      - ID_1
      - ID_2
    
  tasks:
    - name: Set VLANs
      exos_config:
        lines:
          - create vlan "{{ item.value }}"
      loop: "{{ vlan }}"



