---
- name: Network Getting started with playbook
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set SNMP sysName
      exos_command:
        commands:
          - configure snmp sysName {{ "hostname" }}
