---
- name: Network Getting started with playbook
  hosts: all
  connection: network_cli
  ansible_network_os: community.network.exos
  gather_facts: false
  hosts: all

  tasks:
    - name: backup config
      exos_config:
          backup: yes
      register: backup_result
    - name: var_result
      debug:
          var: backup_result.backup_path
    - name: create vlan
      exos_config:
          lines:
              - create vlan "ansible_3"
              - configure vlan ansible_test tag 3
              - configure vlan ansible_test add ports 3 tagged
          save_when: changed
