---
- name: Network Getting started with playbook
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: create vlan
      exos_config:
          lines:
            - configure snmp sysName "{{ inventory_hostname }}"
          save_when: changed
