---
- name: Network Getting started with playbook
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set SNMP sysName
      exos_command:
        commands:
          - configure snmp sysName {{ lookup('env', 'HOSTNAME_ENV') }}
        save_when: changed
      environment:
        HOSTNAME_ENV: "{{ lookup('env', 'MY_HOSTNAME') }}"
