---
- name: Network Getting started with playbook
  hosts: sw1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: create vlan
      exos_config:
          lines:
              - create vlan "ansible_69"
              - configure vlan ansible_test tag 4
              - configure vlan ansible_test add ports 2 tagged
          save_when: changed
